Event.onDomReady(function () {
    window.retailAvailabilitySearchControl = new as.RetailAvailabilitySearchControllerFlex(".pickup-availability", {
        urlOld: "",
        searchUrlOld: "",
        eligibilityUrlOld: "",
        autoCompleteUrl: "/uk/shop/retailStore/autoComplete",
        iconClass: "icon-applestore",
        isAutoCompleteEnabled: false,
        timeout: 30000,
        cookie: {
            name : "rtsid",
            expiry : 180,
            domain : "apple.com",
            enabled : "true"
        },
        storeCookie: "",
        validation: {
            zip : {
                pattern: "^[a-zA-Z][0-9]{1,2}[ ]?[0-9][a-zA-Z]{2}$|^[a-zA-Z][0-9][a-zA-Z][ ]?[0-9][a-zA-Z]{2}$|^[a-zA-Z]{2}[0-9]{1,2}[ ]?[0-9][a-zA-Z]{2}$|^[a-zA-Z]{2}[0-9]?[a-zA-Z][ ]?[0-9][a-zA-Z]{2}$",
                invalidFormatError: "Please enter a valid postcode.",
                requiredError: "Please enter postcode."
            }
        },
        availabilityUnknownError: 'Unavailable for Pickup',
        queryParams : "",
        searchHeader: "Select a location",
        searchPlaceholder: "Search by postcode",
        searchButton: "Search",
        availabilityFor: "Availability for:",
        personalPickup: "<h3 class=\"as-retailavailabilitysearch-infohead h5 strong\" style=\"line-height: 1.1;\">What is Apple Store Pickup?<\/h3>\n<br />\n<p>Simply place your order on apple.com, then pick it up at your favourite Apple Store. We can help you set it up when you arrive, so you\u2019ll be up and running before you leave the store.<\/p>\n<br>\n    <ul>\n        <li>Choose the \u201cPick up\u201d option when you check out, then select an Apple Store near you.<\/li>\n        <li>Products \"Available today\" can usually be picked up within an hour of placing your order.<\/li>\n        <li>You'll receive a notification email when your order is ready to be picked up.<\/li>\n        <li>You can pick up the order yourself, or have someone else pick it up for you.<\/li>\n    <\/ul>",
        previousButton: "Previous",
        nextButton: "Next",
        cancelButton: "Cancel",
        selectButton: "Select",
        searchInputId: "retail-availability-search-query",
        searchInputClass: "query",
        maxlength: 8,
        autocompleteOn: "off",
        autosaveValue: "AppleRetailStoreLocator",
        dataVersion: "1421000640000",
        moreInformation: "More Information",
        storeHoursText: "Store Hours",
        pupLearnMoreText: "",
        pupLearnMoreUrl: "",
        pupLearnMoreA11yText: "",
        isMapEnabled: false,
        mapApiKey: "",
        countryCode: "GB",
        abstractCountryCode: "GB",
        pupEnabled: true,
        isStackOverlay: true,
        personalSetupTextFragmentKey : "<span>Free Personal Setup available in store.<\/span>\n<a id=\"personal-setup-link\" href=\"https://www.apple.com/uk/retail/personalsetup/\" target=\"_blank\">Learn more\n<span class=\"a11y\">Learn more about personal setup, Link opens in a new window.\n<\/span><\/a>",
        personalPickupTextFragmentkey : "<span>You can also choose a pickup point in checkout<\/span>\n<a href=\"http://www.apple.com/uk/shop/browse/home/shipping_pickup\" data-slot-name=\"footer\" data-feature-name=\"Astro Link\" data-display-name=\"AOS: www.apple.com/uk/shop/browse/home/shipping_pickup\" id=\"retail-availability-search-pup-link\" class=\"retail-availability-search-link\" target=\"blank\">Learn more\n<span class=\"a11y\">Learn more about pickup point, Link opens in a new window.<\/span><\/a>",
        mowSearchHeader : "Pickup Availability",
        mowSelectButton: "Continue",
        storeDetailsVoText: "Link opens in a new window",
        storeDetailsText: "Store Details",
        closebuttonVOText: "Close Store Details",
        searchHeaderAlly: "for",
        url: "/uk/shop/retail/pickup-message",
        eligibilityUrl: "/uk/shop/retail/pickup-eligibility",
        searchUrl: "/uk/shop/retail/pickup-message",
        requestDeliveryForNewParts: false,
        littleApuEnabled: true,
        singleStoreCountry: "false",
        pickupStoreAddressFormat: [["companyName"], ["street"], ["street2"], ["street3"], ["city"], ["postalCode"], ["country"], ["daytimePhone"]],
        productModelObserver: new can.Map({}),
        doParamRestriction: true,
        maxParamsPerURL: 3
    });
});